import { Shell } from "@/components/shell";
import { Feedback } from "@/components/feedback";
import { createOrderAction, receiveOrderAction } from "@/lib/actions";
import { readDatabase } from "@/lib/repository";
import { formatMoney } from "@/lib/format";

export default async function Procurement({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const data = await readDatabase();
  return <Shell eyebrow="Операції постачання" title="Керування закупівлями"><Feedback searchParams={searchParams}/><section className="split equal"><div className="panel"><p className="eyebrow">Нове зобов’язання</p><h2>Створити замовлення на закупівлю</h2><form action={createOrderAction} className="form-grid"><label>Постачальник<select name="supplierId">{data.suppliers.map((s) => <option key={s.supplierId} value={s.supplierId}>{s.companyName}</option>)}</select></label><label>Матеріал<select name="materialId">{data.rawMaterials.map((m) => <option key={m.materialId} value={m.materialId}>{m.materialName}</option>)}</select></label><label>Кількість<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Ціна за одиницю<input name="unitPrice" type="number" min="0.01" step="0.01" required/></label><button className="button primary">Оформити замовлення</button></form></div><div className="panel accent-panel"><p className="eyebrow">Принцип приймання</p><h2>Кожне постачання можна простежити</h2><p>Приймання оновлює замовлення, залишок, стан якості та журнал рухів у межах однієї послідовної транзакції.</p><div className="flow"><span>Замовлення</span><b>→</b><span>Контроль якості</span><b>→</b><span>Журнал</span></div></div></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">Книга замовлень</p><h2>Відстеження закупівель</h2></div></div><div className="table-wrap"><table><thead><tr><th>Замовлення</th><th>Постачальник</th><th>Матеріал</th><th>Виконання</th><th>Вартість</th><th>Приймання</th></tr></thead><tbody>{[...data.purchaseOrders].reverse().map((order) => { const line = order.items[0]; const supplier = data.suppliers.find((s) => s.supplierId === order.supplierId); const material = data.rawMaterials.find((m) => m.materialId === line.materialId); const remaining = line.quantityOrdered - line.quantityReceived; return <tr key={order.poId}><td><strong>{order.poNumber}</strong><small>{order.status}</small></td><td>{supplier?.companyName}</td><td>{material?.materialName}</td><td>{line.quantityReceived} / {line.quantityOrdered}</td><td>{formatMoney(order.totalCost)}</td><td>{remaining > 0 ? <form action={receiveOrderAction} className="inline-form"><input type="hidden" name="poId" value={order.poId}/><input aria-label={`Отримана кількість для ${order.poNumber}`} name="quantity" type="number" min="0.01" max={remaining} step="0.01" placeholder={`макс. ${remaining}`} required/><button className="button small">Оприбуткувати</button></form> : <span className="badge healthy">Виконано</span>}</td></tr>; })}</tbody></table></div></section></Shell>;
}
